### ISSUE TITLE
Is this repository deprecated, unmaintained ?

### ISSUE THREAD

**Issue by gzp79** [cloudflare/pages-action#131] opened 2024-06-22 11:57 UTC
There was no update for quite a while and there is no fix for such critical changes as the node 16 deprecation on github.
If this action is unmaintained, could we have some reference to the suggested solution, migration guide ?

Thanks

**Comment by nprogers** [comment] 2024-07-02 15:56
We are in the process of deprecating this repo. We recommend using https://github.com/cloudflare/wrangler-action 

Thanks for your patience and support! We will have a migration guide shortly

cc @nevikashah

**Comment by chrisspiegl** [comment] 2024-07-02 16:00
Hi @nprogers, thank you for the update and guiding us to the current solution.

Maybe, don't close this issue, though… and Pin it instead? So that people coming to this repo see this while looking for their solutions.

As I assume, the deprecation process itself will be a bit more time-consuming.

**Comment by nprogers** [comment] 2024-07-02 18:26
Thank you, @chrisspiegl !

**Comment by gzp79** [comment] 2024-07-06 08:05
> Thanks for your patience and support! We will have a migration guide shortly
> 

Could you please add a one liner to the read-me ? I think that's a better solution than keeping the ticket open. Something like: please consider using our new action as we are planning the deprecate the repository... If the new action is not suitable for ypu please let us know to improve... The usual info as most search result/blog still points to this repository and its a bit confusing.

**Comment by Cherry** [comment] 2024-07-18 23:49
@nprogers Can we please get some idea of the timeline for this deprecation?

There are years of issues and PRs in this repo that have remained unaddressed. Will these be addressed before the deprecation? 

Users have been left for years unknowing about the state of this action, despite it continuing to be suggested in docs, blogs, and other tutorials. If you're going to deprecate this, I really think you need to take some time to address all the outstanding issues and your wonderful early adopters and community contributors who have tried to keep this project maintained, despite their efforts remaining ignored.

**Comment by nprogers** [comment] 2024-10-21 18:37
We've gone through the issues, and are internally working through two main issues that could block some users from fully migrating:

- wrangler-action currently does not provide the same outputs as pages-action for Pages project deployments. If your workflows depend on these outputs, you may need to make temporary adjustments. Rest assured, we’re working to bring these outputs to wrangler-action soon. You can track our progress in this [issue](https://github.com/cloudflare/wrangler-action/issues/300).
- The "Deployment" feature available in pages-action, which lets you view a list of past deployments, is not yet available in wrangler-action, but we plan to add this in a future release of wrangler-action. You can track our progress in this [issue](https://github.com/cloudflare/wrangler-action/issues/301).


For most other issues, functionality exists in wrangler-action or the issue is stale. If there are any issues that have been overlooked, we ask that users open a bug in [wrangler-action](https://github.com/cloudflare/wrangler-action).

**Closed by nprogers** 2024-10-21 18:37 UTC
